### ISSUE TITLE
Error in `keyframes`

### ISSUE THREAD

**Issue by j1anb1n** [reworkcss/rework#108]
rework version: 0.17.3

code:

css:

``` css
@-ms-keyframes spin {
  /* line 220, ../scss/cms/_font.scss */
  0% {
    -ms-transform: rotate(0deg);
  }

  /* line 221, ../scss/cms/_font.scss */
  100% {
    -ms-transform: rotate(359deg);
  }
}
```

javascript

``` javascript
rework(css)
    .use(rework.url(function () {
        ...
    });
```

Error stack:

```
TypeError: Cannot call method 'forEach' of undefined    
at func (/Users/jianbin/developer/thor/node_modules/rework/lib/plugins/function.js:48:16)    
at module.exports (/Users/jianbin/developer/thor/node_modules/rework/lib/plugins/function.js:19:9)    
at /Users/jianbin/developer/thor/node_modules/rework/node_modules/rework-visit/index.js:28:9    
at Array.forEach (native)   
at /Users/jianbin/developer/thor/node_modules/rework/node_modules/rework-visit/index.js:27:22    
at Array.forEach (native)    
at Object.visit [as declarations] (/Users/jianbin/developer/thor/node_modules/rework/node_modules/rework-visit/index.js:18:14)    
at module.exports (/Users/jianbin/developer/thor/node_modules/rework/lib/plugins/function.js:17:11)    
at Rework.use (/Users/jianbin/developer/thor/node_modules/rework/lib/rework.js:58:3)   
at Builder.module.exports.Builder.build (/Users/jianbin/developer/thor/builder/css.js:44:18)",
```

if I **remove the comments**, that will be ok.
