### ISSUE TITLE
cascading `!important`

### ISSUE THREAD

**Issue by tomByrer** [reworkcss/rework#120]
Inserting `!important` after a selector will postfix that tag after each item in that branch.  EG if you want all anchor styling in these rules to have precedence:

``` css
ul
  margin: 0
  li
    list-style: none
    a !important
      display: block
      text-decoration: none
      padding: 5px 10px
      &:hover
        text-decoration: underline
```

results:

``` css
ul {
  margin: 0
}

ul li a:hover {
  text-decoration: underline !important
}

ul li a {
  display: block !important;
  text-decoration: none !important;
  padding: 5px 10px !important
}

ul li {
  list-style: none
}
```

Can be a time-saver for some.
