### ISSUE TITLE
querySelect plugin?

### ISSUE THREAD

**Issue by stevenvachon** [reworkcss/rework#159]
To avoid using jsdom for HTML+CSS parsing, it'd be great if Rework had, in the core or in a plugin, the ability to retrieve a stylesheet via a selector.

If we parsed this with Rework:

``` css
body > a {color:red}
a {font-weight:bold}
a.test {font-style:italic}
```

and queried:

``` js
rework.query("body > a.test");  // or similar
```

it would return:

``` js
{ color:"red", font-style:"italic", font-weight:"bold" }  // pseudo
```
