### ISSUE TITLE
Calculations

### ISSUE THREAD

**Issue by ai** [reworkcss/rework#40]
Calcultaions in CSS is very easefull.

``` css
li {
  width: 726px / 3;
}
```

Because robots are ours slaves, they must think and suffer, not.

Of course, it not only about lazy. We can use it in some automatization in future:

``` css
.logo {
  width: image-width('logo.png') / 2;
}
```

Or in generate `background-size` for retina sprite. Or use with references:

``` css
.preview {
  width: 150px;
  height: @width * 2;
}
```

But, of course, we can just use `calc()`, but it is too long and not every browser support it.

I think, most architectural way will be:
- We have some preprocessor, that wrap any calculation `726px / 3` or `3px + 5em` to `calc()`.
- Rework filter, that find `calc()` without different units (like `726px / 3` or `30px + 172px`) and calculate it now.
