### ISSUE TITLE
Placeholder extend leaves empty selector

### ISSUE THREAD

**Issue by kristoferjoseph** [reworkcss/rework#46]
Using placeholder extension leaves an empty selector in the output.
An example of this can be seen in the test file:
https://github.com/visionmedia/rework/blob/master/test/fixtures/extend.nested.placeholder.out.css

Expected result seems like it would be either to insert `background: black;` or to remove the empty selector if the generated extended selectors cover that case in the cascade.  
### Steps to reproduce
1. Create a placeholder selector:
   
   ``` css
   %dark-button {
       background: black;
   }
   
   .button {
       extend: %dark-button;
   }
   ```
2. Run rework use extend
3. Compare output
### Expected result

``` css
.button {
    background: black;
}
```
### Actual result

``` css
.button {
    background: black;
}

.button {

}
```
