### ISSUE TITLE
CSS stringify omits last semicolon in property declarations

### ISSUE THREAD

**Issue by kristoferjoseph** [reworkcss/rework#49]
After running rework on a css file the last property in the declarations is missing a semicolon.
## Steps to reproduce
1. run rework on a css file

``` css
.foo {
    background: var(var-background-color);
    border: 1px solid var(var-border-color);
}
```
1. Observe results
## Expected results

``` css
.foo {
    background: blue;
    border: 1px solid black;
}
```
## Actual results

``` css
.foo {
    background: blue;
    border: 1px solid black
}
```

_*notice the semicolon is missing_
