### ISSUE TITLE
Media Query de-nester

### ISSUE THREAD

**Issue by ForbesLindesay** [reworkcss/rework#63]
It would be really useful to have a rework that removes nested `@media` rules:

``` css
@media screen and (min-width: 480px) {

    body{
        background-color:#6aa6cc;
        color:#000;    
    }

    @media screen and (min-width: 768px) {

        body{
            background-color:#000;
            color:#fff;    
        }
    }
}
```

becomes

``` css
@media screen and (min-width: 480px) {

    body{
        background-color:#6aa6cc;
        color:#000;    
    }
}
@media screen and (min-width: 768px) {
    body{
        background-color:#000;
        color:#fff;    
    }
}
```

but it would need to be much more clever when the inner media query doesn't imply the outer media query.
