### ISSUE TITLE
Don't change indentation

### ISSUE THREAD

**Issue by ai** [reworkcss/rework#72]
When I proccess

``` css
body {
    transition: all 1s ease-out;
}
```

or

``` css
body { transition: all 1s ease-out }
```

Rework will remove all my formatation and use own styles (without `\n` at end file):

``` css
body {
  transition: all 1s ease-out
}
```

It's not critical, but good postprocessor will change only that, you need.
