### ISSUE TITLE
prefix selectors

### ISSUE THREAD

**Issue by yields** [reworkcss/rework#73]
I will be happy to implement this if you want, just need some pointers

this

``` css
::placeholder {
  color: #aaa
}
```

should eql

``` css
::-webkit-input-placeholder,
::-moz-placeholder,
::-ms-input-placeholder,
::-o-placeholder {
  color: #aaa
}
```
