### ISSUE TITLE
Rework crashes on comments

### ISSUE THREAD

**Issue by finalclass** [reworkcss/rework#76]
Here is my css:

``` css
.login-form {
    /*width: 500px;*/
    height: 200px;
    padding: 42px 0 0 0;
    margin: 0 auto;
}
```

And my rework function:

``` js
function (css) {
  return rework(css).toString();
}
```

When i compile it I get:

```
TypeError: Cannot call method 'map' of undefined
at Compiler.rule (/home/sel/Dokumenty/motim/mtm-www/node_modules/rework/node_modules/css/node_modules/css-stringify/index.js:162:25)
at Compiler.visit (/home/sel/Dokumenty/motim/mtm-www/node_modules/rework/node_modules/css/node_modules/css-stringify/index.js:44:15)
at Array.map (native)
at Compiler.compile (/home/sel/Dokumenty/motim/mtm-www/node_modules/rework/node_modules/css/node_modules/css-stringify/index.js:30:32)
at Object.module.exports [as stringify] (/home/sel/Dokumenty/motim/mtm-www/node_modules/rework/node_modules/css/node_modules/css-stringify/index.js:12:32)
at Rework.toString (/home/sel/Dokumenty/motim/mtm-www/node_modules/rework/lib/rework.js:86:14)
(...)
```

If i remove the comments everything works fine.
