### ISSUE TITLE
References plugin look for references in urls

### ISSUE THREAD

**Issue by simme** [reworkcss/rework#90]
Given the following CSS

``` css
.logo {
  background: url('/gfx/logo@2x.png');
}
```

Gives `Error: @2x is not defined in this scope.` when using the references plugin.
