### ISSUE TITLE
The Extend plugin breaks on interleaved @media-queries.

### ISSUE THREAD

**Issue by simme** [reworkcss/rework#91]
Given a stylesheet like this:

``` css
%foo {
  color: #000
}

body {
  background: #fff
}

@media screen and (min-width: 600px) {
  body {
    background: #eee
  }
}

button {
  extends: %foo
}
```

The extend on button is never processed.
